# ---------------------------------------------------------------------------
# Parity report
#
# Every result this environment produces carries an asterisk, and the asterisk
# needs to be legible months later. This renders what the infrastructure
# actually is, alongside what production is, so a reader can tell which
# differences were deliberate.
#
# It covers the AWS layer only. The application-side values — JVM flags,
# connection pool size, log level, IdP type — are Ansible's, and belong in the
# same document; the placeholder section is where they land.
# ---------------------------------------------------------------------------

locals {
  parity_report = <<-EOT
    # Parity report — ${local.name}

    Generated by OpenTofu. Records what this environment is, against what
    production is, so every run's results can be read with the right caveats.

    ## Compute

    | | This environment | Production |
    |---|---|---|
    | App server | ${var.app_instance_class} (fixed) | t3.large (burstable, unlimited) |
    | ETL | ${var.enable_etl ? var.etl_instance_class : "absent"} (fixed) | t3.small (burstable, unlimited) |
    | Database | ${var.db_instance_class} (fixed) | db.t4g.large (burstable, unlimited) |
    | Read replica | ${var.enable_read_replica ? var.replica_instance_class : "absent"} | db.t4g.medium |
    | Architecture | arm64 | x86_64 app, arm64 database |

    **Deliberate deviation:** production is burstable in unlimited mode, so it
    does not throttle — but a load test is the sustained-CPU workload that
    maximises surplus-credit charges, and a fixed instance removes a variable
    from every run.

    ## Storage and I/O

    | | This environment | Production |
    |---|---|---|
    | Allocated | ${var.db_allocated_storage} GiB | 300 GiB |
    | Type | gp3 | gp3 |
    | Baseline | 3000 IOPS / 125 MiB/s | 3000 IOPS / 125 MiB/s |
    | Autoscaling | **disabled** | enabled (max 1000 GiB) |
    | Multi-AZ | ${var.db_multi_az} | false |
    | Postgres | ${var.db_engine_version} | 16.8 primary, 16.13 elsewhere |

    **I/O parity holds** because any allocation in the 20-399 GiB band gives the
    same 3000 IOPS / 125 MiB/s. The size difference is capacity, not
    performance. **Autoscaling is off deliberately**, and this is a deviation:
    production could grow past 400 GiB and quadruple its own storage I/O.

    ## Edge

    | | This environment | Production |
    |---|---|---|
    | Scheme | internal | internet-facing |
    | Idle timeout | ${var.alb_idle_timeout}s | 300s |
    | TLS | ${var.acm_certificate_arn == null ? "**none — HTTP listener**" : "ACM"} | HTTPS |
    | WAF rate limit | ${var.waf_rate_limit} | 550 |
    | Injector exemption | scope-down statement, other rules still evaluated | n/a |

    ## Database parameters

    - max_connections: ${var.db_max_connections} (production peaks at 122-130)
    - autovacuum: ${var.db_autovacuum} (on for realism; a known source of run-to-run variance)
    - pg_stat_statements, pg_prewarm preloaded; slow query log at 1000ms

    ## To be completed by the deploying side

    - JVM flags (production: -Xms2560m -Xmx5120m server, -Xms1228m -Xmx1228m ETL)
    - Connection pool size (must be set explicitly, not left at the Tomcat default)
    - Log level
    - AVNI_IDP_TYPE
    - New Relic agent attached: required, for parity as much as for metrics
    - Whether this run had a concurrent ETL cycle
    - Tenancy model: shared or dedicated
    - Index state: post-load indexes are pristine; production's carry accumulated bloat
  EOT
}

resource "local_file" "parity" {
  content  = local.parity_report
  filename = "${path.root}/parity-report.md"
}
