---

- name: Perform apt dist-upgrade
  become: true
  apt: update_cache={{ update_apt_cache }}
    upgrade=dist
  tags:
    - packages
    - skip_ansible_lint

- name: Install base packages
  apt: name={{ packages }} update_cache={{ update_apt_cache }} state=present
  become: true
  vars:
    packages:
      - software-properties-common
      - debconf-utils
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm-dev
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk8.6-dev
      - libffi-dev
      - liblzma-dev
      - git
      - curl
      - net-tools
      - zip
      - acl
      - fuse
      - snapd
      - vim
  tags:
    - packages
    - packages.security

- name: Create cache dir for the rest
  become: true
  file: state=directory path={{ avni_cache_dir }} mode=777
