---

  app_container_name: "{{ metabase_container_name }}"
  app_container_image: "{{ metabase_container_image }}"
  app_hostname: "{{ metabase_hostname }}"
  app_container_healthcheck_cmd: "{{ metabase_container_healthcheck_cmd }}"
  app_container_ports_mapping: "{{ metabase_container_ports_mapping }}"
  app_container_env_file: "{{ metabase_container_env_file }}"
  app_container_env_template_file: "{{ metabase_container_env_template_file }}"
  app_container_log_driver: "{{ metabase_container_log_driver }}"
  app_container_log_options: "{{ metabase_container_log_options }}"
  app_container_etc_hosts: "{{ metabase_container_etc_hosts }}"
  app_container_runtime: "{{ metabase_container_runtime }}"
