---

# Application settings.
application_name: "{{ avni_appserver_application_name }}"
app_description: Avni server
application_jar_name: avni-server.jar
application_jar_opts: "{{ avni_server_opts }}"
application_user: "{{avni_appserver_user}}"
application_group: "{{avni_appserver_group}}"
public_url: "{{avni_appserver_app_url}}"
db_url: "{{avni_appserver_db_url}}"
db_name: "{{avni_appserver_db_name}}"
db_user: "{{avni_appserver_db_user}}"
db_password: "{{avni_appserver_db_password}}"
appserver_port: "{{avni_appserver_port}}"
service_dir: "{{avni_service_dir}}"
