---
- name: "Install postgres"
  apt:
    name: ['postgresql', 'postgresql-contrib', 'postgresql-client']
    state: present

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql
