---

- name: Ensure snapd service is started
  service: name=snapd state=started enabled=yes

- name: Install certbot
  snap:
    name: certbot
    classic: yes

- name: Create symbolic link for certbot
  file:
    src: "/snap/bin/certbot"
    dest: "/usr/bin/certbot"
    state: link
