application_name: "{{ int_appserver_application_name }}"
app_description: Avni Integration webapp
webapp_zip_path:  "{{ lookup('env','WEBAPP_ZIP_PATH') }}"
webapp_zip_file_name: "{{ lookup('env','WEBAPP_ZIP_FILE_NAME') }}"
public_url: "{{int_appserver_app_url}}"
application_dir: "/opt/{{ int_appserver_application_name }}"
