---
- name: Create deployment directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: '0755'
  become: yes
  loop:
    - "{{ application_dir }}"
    - "{{ mcp_backup_dir }}"
    - "{{ application_log_dir }}"

- name: Create new deployment directory
  file:
    path: "{{ application_dir }}/current"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: '0755'
  become: yes