---
- name: Check deployable exists
  ansible.builtin.stat:
    path: "{{webapp_zip_path}}/{{webapp_zip_file_name}}"
  register: st

- name: Fail if deployable does not exist
  ansible.builtin.fail:
    msg: "Deployable not present at {{webapp_zip_path}}/{{webapp_zip_file_name}}"
  when: not st.stat.exists

- name: Clean deploy directory
  command: "sudo rm -rf /var/www/{{application_name}}"

- name: Delete deploy directory
  file:
    path: "/var/www/{{application_name}}"
    state: absent
  tags: deploy-app-only

- name: Ensure deploy directory exists
  file:
    path: "/var/www/{{application_name}}"
    owner: "www-data"
    group: "www-data"
    state: directory
    mode: '755'
  tags: deploy-app

- name: Extract web application
  unarchive:
    remote_src: no
    src: "{{webapp_zip_path}}/{{webapp_zip_file_name}}"
    dest: "/var/www/{{application_name}}"
    owner: "www-data"
    group: "www-data"
  tags: deploy-app-only