---

- name: Set up LAHI Glific GCP BigQuery credentials
  template:
    src: lahi_glific_gcp_bigquery_conf.json.j2
    dest: "{{lahi_glific_gcp_project_credentials_path}}"
    owner: root
    group: root
    mode: '644'

- name: "Deploy Integration Server"
  include_role:
    name: appserver
