---

application_group: rules-server-group
application_user: rules-server-user

application_name: "rules-server"
application_dir: "/opt/{{ application_name }}"
application_zip_path: "/tmp"
application_zip_file_name: "rules-server.zip"

pm2_path: "/home/{{ application_user }}/.nvm/versions/node/v10.24.1/bin/pm2"

openchs_upload_user_user_name: "upload-user"
