---

- name: Ensure application directory exists
  file:
    path: "{{ application_dir }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory
    mode: '755'

- name: Ensure recursive directory permissions
  file:
    path: "{{ application_dir }}"
    recurse: yes
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory
