---

- name: Install nvm
  shell: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    creates: "/home/{{ application_user }}/.nvm"

- name: Install the right node version
  command: bash -ilc 'nvm install 10.24.1'
  args:
    creates: "/home/{{ application_user }}/.nvm/versions/node/v10.24.1"


- name: Install pm2
  command: bash -ilc "/home/{{ application_user }}/.nvm/versions/node/v10.24.1/bin/npm i -g pm2"
  args:
    creates: "/home/{{ application_user }}/.nvm/versions/node/v10.24.1/bin/pm2"

