---

- name: Ensure server stopped
  become_user: "{{ application_user }}"
  become: yes
  command: bash -ilc "{{ pm2_path }} stop {{ application_name }} || :"

- name: Delete application directory recursively
  file:
    path: "{{application_dir}}"
    state: absent

- name: Ensure application directory exists
  file:
    path: "{{application_dir}}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory
    mode: '755'

- name: Extract application
  unarchive:
    remote_src: yes
    src: "{{application_zip_path}}/{{application_zip_file_name}}"
    dest: "{{ application_dir }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    extra_opts:
      - '-:'  # This is to make it not fail when faced warnings: https://github.com/ansible/ansible/issues/30976 .The  -:  option  lets  unzip  switch  back to its previous, more liberal behaviour, to allow exact extraction of (older) archives.