---
- name: Check deployable exists
  ansible.builtin.stat:
    path: "{{application_zip_path}}/{{application_zip_file_name}}"
  register: st

- name: Fail if deployable does not exist
  ansible.builtin.fail:
    msg: "Deployable not present at {{application_zip_path}}/{{application_zip_file_name}}"
  when: not st.stat.exists

- name: Ensure server stopped
  become_user: "{{ application_user }}"
  become: yes
  command: bash -ilc "{{ pm2_path }} stop {{ application_name }} || :"

- name: Delete application directory recursively
  file:
    path: "{{application_dir}}"
    state: absent

- name: Ensure application directory exists
  file:
    path: "{{application_dir}}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory
    mode: '755'

- name: Extract application
  unarchive:
    remote_src: no
    src: "{{application_zip_path}}/{{application_zip_file_name}}"
    dest: "{{ application_dir }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
