---

- name: Install dependencies
  apt: name={{ dependencies }} update_cache={{ update_apt_cache }} state=present
  vars:
    dependencies:
      - make
      - openssl
      - python3-pip
      - unzip
      - awscli
