---

- name: Configure integration servers aws
  hosts: webservers
  become: yes
  become_user: root
  remote_user: "{{ application_user }}"
  vars:
    update_apt_cache: yes
  roles:
    - base
    - security
    - javaserver
    - web
