---

- name: Configure webservers servers
  hosts: webservers
  become: yes
  become_user: root
  remote_user: "{{ application_user }}"
  vars:
    update_apt_cache: yes
  vars_files:
    - ./group_vars/prod_vars.yml
    - ./group_vars/prod-secret-vars.yml
  roles:
#    - base
#    - security
#    - jdk
#    - web
#    - int_appserver
#    - nginx
#    - certbot
    - nginx_appserver
