---

- name: Configure webservers servers
  hosts: webservers
  become: yes
  become_user: root
  remote_user: "{{ application_user }}"
  vars:
    update_apt_cache: yes
  vars_files:
    - ./group_vars/vars.yml
  roles:
    - base
    - security
    - nginx
    - certbot
    - postgres
    - web
    - appserver
