---

env: on-premise
#Common variables
ufw_allowed_ports:
  - "22"
  - "80"
  - "443"
  - "3000"
  - "8021"

## ETL server variables
etl_appserver_app_url: "app.security.lfe.avniproject.org"

bugsnag_stage: "on-premise"

etl_allowed_origins: "app.security.lfe.avniproject.org"
avni_idp_type: "keycloak"
scheduled_job_trigger_misfire_threshold: "2700000"
scheduled_job_repeat_interval: "60"
avni_server_host: "localhost"
avni_server_port: "8021"
avni_server_opts: "\" -Dlogging.file={{avni_server_access_log_dir}}/chs.log -Dlogging.path={{avni_server_access_log_dir}} -Dlogging.file.max-size=5mb -Xmx1512m -XX:ErrorFile={{avni_server_access_log_dir}}/jvm.log -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -XX:-OmitStackTraceInFastThrow\""
avni_server_db_host: "db.security.lfe.avniproject.org"
avni_server_db_port: "5432"
avni_server_db_schema: "public"
avni_server_mode: "onPremise"
avni_server_media_bucket_name: "security-user-media"
avni_server_static_content_path: "/var/www/avni_server/"
avni_server_minio_enabled: "true"
avni_server_minio_url: "https://minio.security.lfe.avniproject.org:442"
avni_server_bugsnag_release_stage: "on-premise"
avni_server_keycloak_url: "https://keycloak.security.lfe.avniproject.org"
avni_server_keycloak_enabled: "true"
avni_server_access_log_dir: "/var/log/avni_server/"
avni_server_cache_max_entries: "100"
avni_server_cache_ttl_seconds: "600"
avni_server_cache_max_weight: "1000"
avni_server_show_sql: "false"
avni_server_idp_type: "keycloak"
avni_server_etl_service_origin: "https://app.security.lfe.avniproject.org/etl"
avni_csrf_enabled: "true"
avni_web_validhosts: "app.lfe.security.avniproject.org"
openchs_csp_allowed_hosts: "keycloak.security.lfe.avniproject.org minio.security.lfe.avniproject.org"
avni_enhanced_validation: "true"
avni_blacklisted_urls_file_path: "/etc/avni_blacklisted_urls.json"
