---

env: on-premise
#Common variables
ufw_allowed_ports:
  - "22"
  - "80"
  - "443"
  - "3000"
  - "8021"
  - "8022"
  - "8023"

## ETL server variables
etl_appserver_app_url: "etl.security.lfe.avniproject.org"

bugsnag_stage: "on-premise"
int_appserver_app_url: "etl.security.lfe.avniproject.org"
etl_allowed_origins: "https://app.security.lfe.avniproject.org"
avni_idp_type: "keycloak"
avni_endpoint_end_of_life_1: ""
scheduled_job_trigger_misfire_threshold: "2700000"
scheduled_job_repeat_interval: "60"
avni_server_host: "localhost"
avni_server_port: "8021"
avni_server_opts: " -Dlogging.file.name={{avni_server_access_log_dir}}/chs.log -Dlogging.logback.rollingpolicy.max-file-size=5mb -Dlogging.logback.rollingpolicy.max-history=90 -Xmx1512m -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=\"/bin/kill -9 %p\" -XX:HeapDumpPath=/var/log/avni_server/ -XX:ErrorFile={{avni_server_access_log_dir}}/jvm.log -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -XX:-OmitStackTraceInFastThrow"
avni_server_db_host: "db.security.lfe.avniproject.org"
avni_server_db_port: "5432"
avni_server_db_schema: "public"
avni_server_mode: "onPremise"
avni_server_media_bucket_name: "security-user-media"
avni_server_static_content_path: "/var/www/avni_server/"
avni_server_minio_enabled: "true"
avni_reporting_metabase_self_service_enabled: "false"
avni_server_minio_url: "https://minio.security.lfe.avniproject.org:442"
avni_server_bugsnag_release_stage: "on-premise"
avni_server_keycloak_url: "https://keycloak.security.lfe.avniproject.org"
avni_server_keycloak_enabled: "true"
avni_server_access_log_dir: "/var/log/avni_server"
avni_server_cache_max_entries: "100"
avni_server_cache_ttl_seconds: "600"
avni_server_cache_max_weight: "1000"
avni_server_show_sql: "false"
avni_server_idp_type: "keycloak"
avni_server_etl_service_origin: "https://etl.security.lfe.avniproject.org/etl"
avni_csrf_enabled: "true"
avni_web_validhosts: "app.security.lfe.avniproject.org"
openchs_csp_enabled: "true"
openchs_csp_allowed_hosts: "\"keycloak.security.lfe.avniproject.org minio.security.lfe.avniproject.org\""
avni_enhanced_validation: "true"
avni_blacklisted_urls: '["/profile/**", "/manifest.json"]'
avni_blacklisted_urls_file_path: "/etc/avni_blacklisted_urls.json"
avni_send_exception_in_response: "false"
avni_webapp_timeout: "21600"
avni_server_legacy_longitudinal_export_limit: "30000"

## Metabase properties
mb_password_complexity: "strong"
mb_password_length: "12"
mb_jetty_port: "3000"
mb_db_type: "postgres"
mb_db_port: "5432"
java_timezone: "Asia/Kolkata"

#java_apt_package: openjdk-17-jdk #for ETL. Comment for avni-server

avni_reporting_system_0_name: ""
avni_reporting_system_0_url: ""
avni_reporting_system_1_name: ""
avni_reporting_system_1_url: ""

## MCP server variables
avni_mcp_server_url: "https://tbd-mcp.avniproject.org"
avni_base_url: "https://tbd.avniproject.org"

# Copilot variables
avni_copilot_enabled: "false"