---

etl_appserver_db_url: "jdbc:postgresql://db.{{org_flavour_domain}}:5432/openchs"
etl_appserver_db_password: "{{avni_db_url}}"
avni_api_url: "https://app.{{org_flavour_domain}}:443"
bugsnag_api_key: "{{bugsnag_key_value}}"

etl_bucket_name: "security-user-media"
etl_bucket_access_key: "{{access_key}}"
etl_bucket_access_secret_key: "{{secret_key}}"
etl_cognito_client_id: "ap-south-1_dummy"
etl_cognito_user_pool: "dummy"

healthcheck_ping_key: "{{health_key}}"

avni_server_db_user: "{{avni_db_user}}"
avni_server_db_password: "{{avni_db_password}}"
avni_server_cognito_user_pool_id: "ap-south-1_dummy"
avni_server_cognito_client_id: "dummy"
avni_server_bugsnag_api_key: "{{bugsnag_key_value}}"
avni_server_iam_username: "staging_app_iam_user"
avni_server_iam_access_key: "dummy"
avni_server_iam_secret_access_key: "dummy"
avni_server_msg91_authkey: "{{msg91_key_value}}"
avni_server_minio_access_key: "{{minio_key}}"
avni_server_minio_secret_access_key: "{{minio_pwd}}"
avni_server_keycloak_client_secret: "{{keycloak_client_secret}}"

openchs_upload_user_password: "{{upload_user_password}}"