---

env: prod
#Common variables
ufw_allowed_ports: "22, 80, 443, 3000"

## Integration server variables
int_appserver_app_url: "int-prod.avniproject.org"
goonj_sf_app_url: "https://goonj--goonjtest.sandbox.my.salesforce.com/services/apexrest/v1"
goonj_sf_auth_url: "https://test.salesforce.com/services/oauth2/token"
goonj_sf_media_url_prefix: "https://app.avniproject.org/web/media?url="
amrit_server_url: "http://amritwprdev.piramalswasthya.org:8080"
goonj_schedule_cron: "0 0 * * * ?"
power_schedule_cron: "0 0 * * * ?"
amrit_schedule_cron: "0 0/2 * * * ?"
goonj_app_tasks: "None"
amrit_app_tasks: "None"
goonj_recreate_dispatch_receipt: "true"

## ETL server variables
etl_appserver_app_url: "int-prod.avniproject.org"

bugsnag_stage: "prod"

etl_allowed_origins: "https://app.avniproject.org,https://int-prod.avniproject.org"
avni_idp_type: "cognito"