---

env: prod
#Common variables
ufw_allowed_ports:
  - "22"
  - "80"
  - "443"
  - "3000"
  - "8021"

## Integration server variables
int_appserver_app_url: "int-prod.avniproject.org"
goonj_sf_app_url: "https://goonj--goonjtest.sandbox.my.salesforce.com/services/apexrest/v1"
goonj_sf_auth_url: "https://test.salesforce.com/services/oauth2/token"
goonj_sf_media_url_prefix: "https://app.avniproject.org/web/media?url="
amrit_server_url: "http://amritwprdev.piramalswasthya.org:8080"
goonj_schedule_cron: "0 0 * * * ?"
power_schedule_cron: "0 0 * * * ?"
amrit_schedule_cron: "0 0/2 * * * ?"
goonj_app_tasks: "None"
amrit_app_tasks: "None"
goonj_recreate_dispatch_receipt: "true"
#TODO set below before go-live
lahi_glific_gcp_project_id: ""
lahi_glific_gcp_dataset_name: ""
lahi_glific_gcp_project_credentials_path: "/etc/lahi_glific_gcp_bigquery_conf.json"
lahi_avni_api_url: "https://app.avniproject.org"
lahi_schedule_cron: "0 0/5 * * * ?"

## ETL server variables
etl_appserver_app_url: "int-prod.avniproject.org"
bugsnag_stage: "prod"
etl_server_opts: " -Dnewrelic.environment=production -javaagent:/opt/newrelic/newrelic.jar"

etl_allowed_origins: "https://app.avniproject.org,https://int-prod.avniproject.org"
avni_idp_type: "cognito"
scheduled_job_trigger_misfire_threshold: "3600000"
scheduled_job_repeat_interval: "90"

avni_server_host: "localhost"
avni_server_port: "8021"
avni_server_opts: " -Dnewrelic.environment=production -javaagent:/opt/newrelic/newrelic.jar -Dlogging.file={{avni_server_access_log_dir}}/chs.log -Dlogging.path={{avni_server_access_log_dir}} -Dlogging.file.max-size=5mb -Xmx1024m -XX:ErrorFile={{avni_server_access_log_dir}}/jvm.log -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -XX:-OmitStackTraceInFastThrow"
avni_server_db_host: "serverdb.openchs.org."
avni_server_db_port: "5432"
avni_server_db_schema: "public"
avni_server_mode: "live"
avni_server_media_bucket_name: "prod-user-media"
avni_server_static_content_path: "/var/www/avni_server/"
avni_server_minio_enabled: "false"
avni_server_minio_url: ""
avni_server_bugsnag_release_stage: "prod"
avni_server_keycloak_url: ""
avni_server_keycloak_enabled: "false"
avni_server_access_log_dir: "/var/log/avni_server"
avni_server_cache_max_entries: "5"
avni_server_cache_ttl_seconds: "10"
avni_server_cache_max_weight: "1000"
avni_server_show_sql: "false"
avni_server_idp_type: "cognito"
avni_server_etl_service_origin: "https://int-prod.avniproject.org/etl"
avni_csrf_enabled: "false"
avni_web_validhosts: ""
openchs_csp_enabled: "false"
openchs_csp_allowed_hosts: ""
avni_enhanced_validation: "false"
avni_blacklisted_urls_file_path: "/etc/avni_blacklisted_urls.json"
avni_send_exception_in_response: "true"
avni_webapp_timeout: "21600"
avni_server_legacy_longitudinal_export_limit: "30000"
avni_blacklisted_urls: '["/profile/**", "/manifest.json"]'

newrelic_app_name: "avni"
newrelic_application_logging_enabled: "false"