---

env: prod
#Common variables
ufw_allowed_ports:
  - "22"
  - "80"
  - "443"
  - "3000"
  - "8021"

## Integration server variables
int_appserver_app_url: "int-prod.avniproject.org"
goonj_sf_app_url: "https://goonj--goonjtest.sandbox.my.salesforce.com/services/apexrest/v1"
goonj_sf_auth_url: "https://test.salesforce.com/services/oauth2/token"
goonj_sf_media_url_prefix: "https://app.avniproject.org/web/media?url="
amrit_server_url: "http://amritwprdev.piramalswasthya.org:8080"
goonj_schedule_cron: "0 0 * * * ?"
power_schedule_cron: "0 0 * * * ?"
amrit_schedule_cron: "0 0/2 * * * ?"
goonj_app_tasks: "None"
amrit_app_tasks: "None"
goonj_recreate_dispatch_receipt: "true"
#TODO set below before go-live
lahi_glific_gcp_project_id: ""
lahi_glific_gcp_dataset_name: "918956411022"
lahi_glific_gcp_project_credentials_path: "/etc/lahi_glific_gcp_bigquery_conf.json"
lahi_avni_api_url: "https://app.avniproject.org"
lahi_schedule_cron: "-"
int_server_opts: " --enable-preview"
rwb_schedule_cron: "-"
rwb_avni_nudge_custom_since_days: "03"
rwb_avni_nudge_custom_within_days: "03"
rwb_avni_api_url: "https://app.avniproject.org"

## ETL server variables
etl_appserver_app_url: "int-prod.avniproject.org"
bugsnag_stage: "prod"
etl_server_opts: " -Dnewrelic.environment=production -javaagent:/opt/newrelic/newrelic.jar"

etl_allowed_origins: "https://app.avniproject.org,https://int-prod.avniproject.org"
avni_idp_type: "cognito"
avni_endpoint_end_of_life_1: "2024-09-27"
scheduled_job_trigger_misfire_threshold: "4800000"
scheduled_job_repeat_interval: "360"

avni_server_host: "localhost"
avni_server_port: "8021"
avni_server_opts: " -Dnewrelic.environment={{ newrelic_environment }} -javaagent:/opt/newrelic/newrelic.jar -Dlogging.file.name={{avni_server_access_log_dir}}/chs.log -Dlogging.logback.rollingpolicy.max-file-size=5mb -Dlogging.logback.rollingpolicy.max-history=90 -Xms2560m -Xmx12288m -XX:MaxMetaspaceSize=512m -XX:CompressedClassSpaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath={{avni_server_access_log_dir}}/ -XX:OnOutOfMemoryError=\"/bin/kill -9 %p\" -XX:ErrorFile={{avni_server_access_log_dir}}/jvm.log -XX:+UseStringDeduplication -XX:-OmitStackTraceInFastThrow"
avni_server_db_host: "serverdb.openchs.org."
avni_server_db_port: "5432"
avni_server_db_schema: "public"
avni_server_mode: "live"
avni_server_media_bucket_name: "prod-user-media"
avni_server_static_content_path: "/var/www/avni_server/"
avni_server_minio_enabled: "false"
avni_reporting_metabase_self_service_enabled: "false"
avni_server_minio_url: ""
avni_server_bugsnag_release_stage: "prod"
avni_server_keycloak_url: ""
avni_server_keycloak_enabled: "false"
avni_server_access_log_dir: "/var/log/avni_server"
avni_server_cache_max_entries: "100"
avni_server_cache_ttl_seconds: "300"
avni_server_cache_max_weight: "3000"
avni_server_show_sql: "false"
avni_server_idp_type: "cognito"
avni_server_etl_service_origin: "https://int-prod.avniproject.org/etl"
avni_csrf_enabled: "false"
avni_web_validhosts: ""
openchs_csp_enabled: "false"
openchs_csp_allowed_hosts: ""
avni_enhanced_validation: "false"
avni_blacklisted_urls_file_path: "/etc/avni_blacklisted_urls.json"
avni_send_exception_in_response: "true"
avni_webapp_timeout: "21600"
avni_server_legacy_longitudinal_export_limit: "30000"
avni_blacklisted_urls: '["/profile/**", "/manifest.json"]'

newrelic_app_name: "avni"
newrelic_environment: "production"
newrelic_agent_enabled: "true"
newrelic_application_logging_enabled: "false"
newrelic_distributed_tracing_enabled: "false"

avni_reporting_system_0_name: "Metabase Reports"
avni_reporting_system_0_url: "https://reporting.avniproject.org"
avni_reporting_system_1_name: "Jasper Reports"
avni_reporting_system_1_url: "https://reporting-jasper.avniproject.org/jasperserver/login.html"
avni_reporting_system_2_name: "Superset Reports"
avni_reporting_system_2_url: "https://reporting-superset.avniproject.org/login/"
avni_reporting_metabase_api_url: "https://reporting.avniproject.org/api"