---

env: staging
#Common variables
ufw_allowed_ports:
  - "22"
  - "80"
  - "443"
  - "3000"
  - "8021"

## Integration server variables
int_appserver_app_url: "int-staging.avniproject.org"
goonj_sf_app_url: "https://goonj--patialv1.sandbox.my.salesforce.com/services/apexrest/v1"
goonj_sf_auth_url: "https://test.salesforce.com/services/oauth2/token"
goonj_sf_media_url_prefix: "https://staging.avniproject.org/web/media?url="
amrit_server_url: "http://amritwprdev.piramalswasthya.org:8080"
goonj_schedule_cron: "0 0/10 * * * ?"
power_schedule_cron: "0 0 * * * ?"
amrit_schedule_cron: "0 0/2 * * * ?"
goonj_app_tasks: "all"
amrit_app_tasks: "None"
goonj_recreate_dispatch_receipt: "true"
lahi_glific_gcp_project_id: "glific-lms-lahi"
lahi_glific_gcp_dataset_name: "918956411022"
lahi_glific_gcp_project_credentials_path: "/etc/lahi_glific_gcp_bigquery_conf.json"
lahi_avni_api_url: "https://app.avniproject.org"
lahi_schedule_cron: "-"

## ETL server variables
etl_appserver_app_url: "int-staging.avniproject.org"

bugsnag_stage: "staging"

etl_allowed_origins: "https://staging.avniproject.org,https://int-staging.avniproject.org"
avni_idp_type: "both"
avni_endpoint_end_of_life_1: "2024-09-05"
scheduled_job_trigger_misfire_threshold: "2700000"
scheduled_job_repeat_interval: "60"
avni_server_host: "localhost"
avni_server_port: "8021"
avni_server_opts: " -Dnewrelic.environment={{ newrelic_environment }} -javaagent:/opt/newrelic/newrelic.jar -Dlogging.file={{avni_server_access_log_dir}}/chs.log -Dlogging.path={{avni_server_access_log_dir}} -Dlogging.file.max-size=5mb -Dlogging.file.max-history=90 -Xmx1512m -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=\"/bin/kill -9 %p\" -XX:HeapDumpPath=/var/log/avni_server/ -XX:ErrorFile={{avni_server_access_log_dir}}/jvm.log -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -XX:-OmitStackTraceInFastThrow"
avni_server_db_host: "stagingdb.openchs.org."
avni_server_db_port: "5432"
avni_server_db_schema: "public"
avni_server_mode: "staging"
avni_server_media_bucket_name: "staging-user-media"
avni_server_static_content_path: "/var/www/avni_server/"
avni_server_minio_enabled: "true"
avni_server_minio_url: "https://minio-staging.avniproject.org:442"
avni_server_bugsnag_release_stage: "staging"
avni_server_keycloak_url: "https://keycloak-staging.avniproject.org"
avni_server_keycloak_enabled: "true"
avni_server_access_log_dir: "/var/log/avni_server"
avni_server_cache_max_entries: "100"
avni_server_cache_ttl_seconds: "600"
avni_server_cache_max_weight: "1000"
avni_server_show_sql: "false"
avni_server_idp_type: "both"
avni_server_etl_service_origin: "https://int-staging.avniproject.org/etl"
avni_csrf_enabled: "false"
avni_web_validhosts: ""
openchs_csp_enabled: "false"
openchs_csp_allowed_hosts: ""
avni_enhanced_validation: "false"
avni_blacklisted_urls: '["/profile/**", "/manifest.json"]'
avni_blacklisted_urls_file_path: "/etc/avni_blacklisted_urls.json"
avni_send_exception_in_response: "true"
avni_webapp_timeout: "21600"
avni_server_legacy_longitudinal_export_limit: "30000"

newrelic_app_name: "avni"
newrelic_environment: "staging"
newrelic_agent_enabled: "false"
newrelic_application_logging_enabled: "false"
newrelic_distributed_tracing_enabled: "false"

avni_reporting_system_0_name: "Metabase Reports"
avni_reporting_system_0_url: "https://reporting.avniproject.org"
avni_reporting_system_1_name: "Jasper Reports"
avni_reporting_system_1_url: "https://reporting-jasper.avniproject.org/jasperserver/login.html"
