---

# Application settings.
application_name: "{{ etl_appserver_application_name }}"
app_description: Avni ETL server
application_jar_name: avni-etl.jar
application_jar_opts: "{{ etl_server_opts }}"
application_user: "{{etl_appserver_user}}"
application_group: "{{etl_appserver_group}}"
public_url: "{{etl_appserver_app_url}}"
db_url: "{{etl_appserver_db_url}}"
db_name: "{{etl_appserver_db_name}}"
db_user: "{{etl_appserver_db_user}}"
db_password: "{{etl_appserver_db_password}}"
appserver_port: "{{etl_appserver_port}}"
service_dir: "{{etl_service_dir}}"
