---
- name: Check deployable exists
  ansible.builtin.stat:
    path: "{{application_zip_path}}/{{application_zip_file_name}}"
  register: st

- name: Fail if deployable does not exist
  ansible.builtin.fail:
    msg: "Deployable not present at {{application_zip_path}}/{{application_zip_file_name}}"
  when: not st.stat.exists

- name: Ensure server stopped
  service:
    name: "{{application_name}}_appserver.service"
    enabled: true
    state: stopped

- name: Copy appserver jar file
  copy:
    remote_src: no
    src: "{{application_zip_path}}/{{application_zip_file_name}}"
    dest: "{{ application_dir }}/{{application_jar_name}}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0755

- name: Ensure server started
  service:
    name: "{{application_name}}_appserver.service"
    enabled: true
    state: started