---

- name: Set up config for application
  template:
    src: appserver.conf.j2
    dest: "{{application_conf_file}}"
    owner: root
    group: root
    mode: '644'

- name: Set up start script for application
  template:
    src: start.sh.j2
    dest: "{{application_dir}}/start.sh"
    owner: "{{application_user}}"
    group: "{{application_group}}"
    mode: '755'

- name: Set up systemd config for application
  template:
    src: appserver.service.template.j2
    dest: "{{service_dir}}/{{application_name}}_appserver.service"
    owner: "{{application_user}}"
    group: "{{application_group}}"
    mode: '755'

- name: Enable server
  service:
    name: "{{application_name}}_appserver.service"
    enabled: true
