kind: Deployment

apiVersion: apps/v1

metadata:
  name: supersetdeployment
  namespace: superset-prod
  labels:
    environment: prod
    app: superset
  annotations:
    kubernetes.io/autoupdate-spec: "work for superset 4.0.1"    # need to change in every deployment
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      environment: prod
      app: superset
  template:
    metadata:
      name: supersetpod
      labels:
        environment: prod
        app: superset
    spec:
      nodeSelector:
        environment: prod
        app: superset
      containers:
        - name: supersetcontainer
          image: public.ecr.aws/m1p7h9p1/avniproject/reporting-superset:4.0.1    # need to change after setting up avni
          env:
            - name: SUPERSET_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: superset-prod-configmap
                  key: SUPERSET_SECRET_KEY
            - name: SUPERSET_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: superset-prod-configmap
                  key: SUPERSET_DB_NAME
            - name: SUPERSET_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: superset-prod-configmap
                  key: SUPERSET_DB_USER
            - name: SUPERSET_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: superset-prod-configmap
                  key: SUPERSET_DB_PASSWORD
            - name: SUPERSET_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: superset-prod-configmap
                  key: SUPERSET_DB_URL
            - name: SUPERSET_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: superset-prod-configmap
                  key: SUPERSET_DB_PORT
