---

- name: Configure webservers servers
  hosts: webservers
  become: yes
  become_user: root
  remote_user: "{{ int_appserver_user }}"
  vars:
    update_apt_cache: yes
  vars_files:
    - group_vars/basic_vars.yml
    - group_vars/prerelease_vars.yml
    - group_vars/prerelease-secret-vars.yml.enc
  roles:
    - base
    - security
    - jdk
#    - web
#    - int_appserver
    - nginx
    - certbot
#    - nginx_appserver
