---

- name: Configure webservers servers
  hosts: webservers
  become: yes
  become_user: root
  remote_user: "{{ int_appserver_user }}"
  vars:
    update_apt_cache: yes
  vars_files:
    - group_vars/basic_vars.yml
    - group_vars/prod_vars.yml
    - group_vars/prod-secret-vars.yml
  roles:
    - base
    - security
    - jdk
    - int_web
    - int_appserver
    - nginx
    - certbot
    - nginx_appserver
