---

- name: Configure reverse proxy servers
  hosts: reverse_proxy
  become: yes
  become_user: root
  remote_user: "{{ application_user }}"
  vars:
    update_apt_cache: yes
  vars_files:
    - group_vars/staging_vars.yml
    - ./group_vars/staging-secret-vars.yml.enc
  roles:
    - base
    - security
    - nginx
    - certbot
    - nginx_appserver

