---

- name: Configure etl servers
  hosts: etlservers
  become: yes
  become_user: root
  remote_user: "{{ etl_appserver_user }}"
  vars:
    update_apt_cache: yes
  vars_files:
    - group_vars/basic_vars.yml
    - group_vars/rwb_prod_vars.yml
    - group_vars/rwb_prod-secret-vars.yml.enc
  roles:
    - base     # Required if int server is not pre deployed.
    - security # Required if int server is not pre deployed.
    - jdk      # Required if int server is not pre deployed.
    - nginx    # Required if int server is not pre deployed.
    - certbot  # Required if int server is not pre deployed.
    - etl_appserver
    - nginx_appserver