install-halyard:
	curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/stable/InstallHalyard.sh
	sudo bash InstallHalyard.sh

update-halyard:
	sudo apt-get update
	sudo apt-get upgrade spinnaker-halyard

setup-halyard

