---

- include_tasks: perform_aptitude_dist_upgrade.yml
  when: perform_aptitude_dist_upgrade is defined and perform_aptitude_dist_upgrade

- include_tasks: create_non_root_sudo_user.yml
  when: application_user != "root"

- include_tasks: setup_unattended_upgrades.yml
  when: enable_unattended_upgrades is defined and enable_unattended_upgrades

- include_tasks: setup_uncomplicated_firewall.yml
  when: enable_ufw is defined and enable_ufw

- include_tasks: setup_fail2ban.yml
  when: enable_fail2ban is defined and enable_fail2ban
