---

- include_tasks: setup_firewall_rules.yml
- include_tasks: setup_nginx.yml
  vars:
    nginx_config_file: "appserver_nginx_conf_initial.j2"
- include_tasks: setup_certificates.yml
- include_tasks: setup_nginx.yml
  vars:
    nginx_config_file: "appserver_nginx_conf_updated.j2"

